name: app_medagenda
description: "Agendamentos para clinicas médicas"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  intl:
  carousel_slider:
  flutter_dotenv:
  confetti:
  timezone: 
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.27.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


assets:
  - .env
  # - fonts/
  - images

flutter:
  uses-material-design: true
  # fonts:
